[project]
name = "simulation"
version = "0.0.0"
authors = [{ name = "Your Name", email = "email@email.com" }]
description = "simulation"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11,<3.12"

dependencies = [
    "isaacsim[all,extscache]==5.0.0",
    "av>=16.0.1",
    "dora-rs-cli>=0.3.13",
    "scipy>=1.10.1",
    "msgs",
]

[project.scripts]
simulation = "simulation.main:main"

[tool.ruff.lint]
extend-select = [
  "D",   # pydocstyle
  "UP"
]


