project: artefacts/go2-isaac-example
version: 0.1.0

jobs:
  waypoint_missions:
    type: test
    timeout: 20 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: isaac_sim
      
    scenarios:
      # Reinstall artefacts-click as a temporary workaround for conflicting click versions
      #   see https://github.com/art-e-fact/artefacts-client/issues/370
      settings:
        - name: report_based_waypoint_mission_test
          run: "rm -rf outputs/artefacts && uv run dataflow --test-waypoint-report"
          output_dirs: ["outputs/artefacts"]
          
        - name: pose_based_waypoint_mission_test
          run: "rm -rf outputs/artefacts && uv run dataflow --test-waypoint-poses"
          output_dirs: ["outputs/artefacts"]
  