project: artefacts/go2-isaac-example
version: 0.1.0

jobs:
  waypoint_missions:
    type: test
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: isaac_sim
      
    scenarios:
      settings:
        - name: report_based_waypoint_mission_test
          run: "rm -rf outputs/artefacts && go2-example --test-waypoint-report"
          output_dirs: ["outputs/artefacts"]
          
        - name: pose_based_waypoint_mission_test
          run: "rm -rf outputs/artefacts && go2-example --test-waypoint-poses"
          output_dirs: ["outputs/artefacts"]
  