project: artefacts/go2-isaac-example
version: 0.1.0

jobs:
  unit_tests:
    type: test
    timeout: 15 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: isaac_sim
      
    scenarios:
      settings:
        - name: navigator_unit_tests
          pytest_file: "nodes/navigator/tests"
          
        - name: policy_controller_unit_tests
          pytest_file: "nodes/policy_controller/tests"
  
  waypoint_missions:
    type: test
    timeout: 20 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: isaac_sim
      
    scenarios:
      settings:
        - name: report_based_waypoint_mission_test
          run: "uv run dataflow --test-waypoint-report"
          
        - name: pose_based_waypoint_mission_test
          run: "uv run dataflow --test-waypoint-poses"
  